Runit works with v7init much better than OpenRC, it allows the X Server to work. Also add the commands v7poweroff and v7reboot, and obsolete rc.status
Signed-off-by: Johnothan King <johnothanking@protonmail.com>

diff --git a/rc b/rc
--- a/rc
+++ b/rc
@@ -1,10 +1,9 @@
 #!/bin/sh
 
+. /etc/profile
 echo "V7 Init on $(uname -sm)" > /dev/console
-export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
-mount -o rw /dev/sda2 /
-mount -o rw /dev/sda1 /boot
-swapon /dev/sda3
+echo "BEGIN: Started V7 Init on $(uname -sm)" > /var/log/v7init.log
+mount -a
 rm -rf /tmp/*
 
 if [ ! -e /etc/hostname ] || [ "$(cat /etc/hostname)" = "" ]; then
@@ -15,5 +14,14 @@ fi
 
 cd /etc/v7init/en
 for scripts in $(ls .); do
-    sh $scripts
+    . $scripts
+    echo "Starting ${NAME}..." > /dev/console
+    echo "info: Starting ${NAME}" >> /var/log/v7init.log
+    start
+    if [ $? != 0 ]; then
+        echo "error: ${NAME} failed to start." >> /var/log/v7init.log
+        echo "${NAME} failed to start!" > /dev/console
+    else
+        echo "success: ${NAME} started successfully." > /dev/console
+    fi
 done
